# -*- coding: utf-8 -*-
"""Cats vs Dogs Classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R6avvW8EBziek7UAR9r8hdbsoZcpF3qz
"""

# CELL 1: Download the Cats vs Dogs images automatically
!wget -q https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
!unzip -q kagglecatsanddogs_5340.zip
!rm kagglecatsanddogs_5340.zip

from keras.src.backend import image
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
from PIL import Image

def remove_corrupt_images(base_dir='PetImages'):
    removed = 0
    for root, _, files in os.walk(base_dir):
        for file in files:
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                path = os.path.join(root, file)
                try:
                    img = Image.open(path)
                    img.verify()
                except Exception:
                    print(f"Removing corrupt: {path}")
                    os.remove(path)
                    removed += 1
    print(f"Removed {removed} corrupt images.")

remove_corrupt_images()

data = ImageDataGenerator(
    rescale = 1./255, # this will only change the brightness of the pixel
    validation_split = 0.2
)

data = ImageDataGenerator(rescale=1./255,
                          validation_split=0.2)

train_generator = data.flow_from_directory(
    'PetImages',
    target_size=(224, 224), # this changes the size of the image
    batch_size=32,
    class_mode='binary',
    subset='training'
)


val_generator = data.flow_from_directory(
    'PetImages',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout


model = Sequential([
    Conv2D(32,(3,3),activation='relu',input_shape=(224,224,3)),
    MaxPooling2D(2,2),

    Conv2D(64,(3,3),activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128,(3,3),activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(512,activation='relu'),
    Dropout(0.4),
    Dense(1,activation='sigmoid')
])

model.summary()

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

history = model.fit(train_generator,epochs=5,validation_data=val_generator)

import joblib
joblib.dump(model, 'cats-vs-dogs.pkl')

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'],label='Train_acc')
plt.plot(history.history['val_accuracy'],label='Test_acc')

plt.legend()
plt.grid()
plt.show()

plt.plot(history.history['loss'],label='Train_loss')
plt.plot(history.history['val_loss'],label='Test_loss')

plt.legend()
plt.grid()
plt.show()

from tensorflow.keras.preprocessing.image import load_img, img_to_array

def predict(path):
    img = load_img(path, target_size=(224, 224))      # load n resize
    x = img_to_array(img) / 255.0                     # to array + normalize
    x = x.reshape(1, 224, 224, 3)                      # adding batch dimension

    p = model.predict(x, verbose=0)[0][0]              # getting the probability

    if p > 0.5:
        print(f"DOG → {p*100:.1f}%")
    else:
        print(f"CAT → {(1-p)*100:.1f}%")

# Use it with just one line each:
# predict("cat.jpg")
# predict("dog.jpg")
# predict("my_photo.jpg")
